export const ADMIN_GET_USERS_REQUEST = "ADMIN_GET_USERS_REQUEST";
export const ADMIN_GET_USERS_SUCCESS = "ADMIN_GET_USERS_SUCCESS";
export const ADMIN_GET_USERS_FAILURE = "ADMIN_GET_USERS_FAILURE";

export const ADMIN_GET_USER_ASSETS_REQUEST = "ADMIN_GET_USER_ASSETS_REQUEST";
export const ADMIN_GET_USER_ASSETS_SUCCESS = "ADMIN_GET_USER_ASSETS_SUCCESS";
export const ADMIN_GET_USER_ASSETS_FAILURE = "ADMIN_GET_USER_ASSETS_FAILURE";

export const ADMIN_GET_USER_WALLET_REQUEST = "ADMIN_GET_USER_WALLET_REQUEST";
export const ADMIN_GET_USER_WALLET_SUCCESS = "ADMIN_GET_USER_WALLET_SUCCESS";
export const ADMIN_GET_USER_WALLET_FAILURE = "ADMIN_GET_USER_WALLET_FAILURE";

export const ADMIN_GET_ORDERS_REQUEST = "ADMIN_GET_ORDERS_REQUEST";
export const ADMIN_GET_ORDERS_SUCCESS = "ADMIN_GET_ORDERS_SUCCESS";
export const ADMIN_GET_ORDERS_FAILURE = "ADMIN_GET_ORDERS_FAILURE";


